# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://blog.me115.com
date_format: "ordinal"
title: 大CC
subtitle: "嘿！北京"
description: "大CC的个人博客"
keywords: 大CC,博客,计算机,互联网,创业,时间管理,个人提升,木书架网
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/me115/me115.github.io

# ---------------- #
#      Author      #
# ---------------- #
author: 大CC
organization: Toutiao, Inc.
organization_url: https://www.toutiao.com
location: Beijing, China
email: me115@126.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: me115
douban_username: me115
facebook_username: me115
weibo_username: me115
zhihu_username: me115
twitter_username: me115

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: me115
disqus_username: me115

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [C++, Python, Golang, Design Patterns]
skill_mobile_app_keywords: [Android, Reverse Engineering]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
popular_repos: ['me115/linuxtools_rst','me115/design_patterns', 'csdncommenter', 'me115/design_patterns' ]
contribute_repos: ['']
